// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxhMMm_upff_oXaSvITE5r7CilHYEagio',
    appId: '1:585549166091:web:ad8981d2dde03009ff390e',
    messagingSenderId: '585549166091',
    projectId: 'medlink360-fd568',
    authDomain: 'medlink360-fd568.firebaseapp.com',
    storageBucket: 'medlink360-fd568.firebasestorage.app',
    measurementId: 'G-GFRELD2VFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWvp-JHtZ_20ePy49wv5qYJzUARZ6_0g',
    appId: '1:585549166091:android:c619099a7c3c2372ff390e',
    messagingSenderId: '585549166091',
    projectId: 'medlink360-fd568',
    storageBucket: 'medlink360-fd568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlH1GsPQf4erdzLPrz5VBrVr-YMunZME',
    appId: '1:585549166091:ios:1bf212e8f3ad738dff390e',
    messagingSenderId: '585549166091',
    projectId: 'medlink360-fd568',
    storageBucket: 'medlink360-fd568.firebasestorage.app',
    iosClientId: '585549166091-3u5ivahiq400t3vc0nm4bp4f6to89pk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlink360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLlH1GsPQf4erdzLPrz5VBrVr-YMunZME',
    appId: '1:585549166091:ios:1bf212e8f3ad738dff390e',
    messagingSenderId: '585549166091',
    projectId: 'medlink360-fd568',
    storageBucket: 'medlink360-fd568.firebasestorage.app',
    iosClientId: '585549166091-3u5ivahiq400t3vc0nm4bp4f6to89pk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.medlink360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxhMMm_upff_oXaSvITE5r7CilHYEagio',
    appId: '1:585549166091:web:54183c89c174b376ff390e',
    messagingSenderId: '585549166091',
    projectId: 'medlink360-fd568',
    authDomain: 'medlink360-fd568.firebaseapp.com',
    storageBucket: 'medlink360-fd568.firebasestorage.app',
    measurementId: 'G-1BC5J1D2HK',
  );
}
